export const MenuItems = [
    {
        title:"Manage",
        url:"/",
        cName:"nav-links"
    },
    {
        title:"OnlineStations",
        url:"/online",
        cName:"nav-links"
    },
    {
        title:"OfflineStations",
        url:"/offline",
        cName:"nav-links"
    }
];

export const ManageItems = [
    {
        title:"Tail",
        cName:"ManNav-links"
    },
    {
        title:"Stations",
        cName:"ManNav-links"
    },
    {
        title:"GDT",
        cName:"ManNav-links"
    },
    {
        title:"Frequency",
        cName:"ManNav-links"
    },
    {
        title:"flight",
        cName:"ManNav-links"
    },
];