export const ManageItems = [
    {
        title:"Tail",
        url:"/tail",
        cName:"manNav-links"
    },
    {
        title:"Stations",
        url:"/stations",
        cName:"manNav-links"
    },
    {
        title:"GDT",
        url:"/gdt",
        cName:"manNav-links"
    },
    {
        title:"Frequency",
        url:"/frequency",
        cName:"manNav-links"
    },
    {
        title:"Flight",
        url:"/flight",
        cName:"manNav-links"
    },
];