export const ManageItems = [
    {
        title:"Tail",
        url:"/tail",
        cName:"nav-links"
    },
    {
        title:"Stations",
        url:"/stations",
        cName:"nav-links"
    },
    {
        title:"GDT",
        url:"/gdt",
        cName:"nav-links"
    },
    {
        title:"Frequency",
        url:"/frequency",
        cName:"nav-links"
    },
    {
        title:"departure",
        url:"/departure",
        cName:"nav-links"
    },
];